links = [
    "https://stat.gov.kz/en/industries/economy/national-accounts/", 
    "https://stat.gov.kz/en/industries/economy/prices/",
    "https://stat.gov.kz/en/industries/economy/stat-kon-obs/",
    "https://stat.gov.kz/en/industries/economy/local-market/",
    "https://stat.gov.kz/en/industries/economy/foreign-market/",
    "https://stat.gov.kz/en/industries/social-statistics/demography/",
    "https://stat.gov.kz/en/industries/social-statistics/stat-medicine/",
    "https://stat.gov.kz/en/industries/social-statistics/stat-crime/",
    "https://stat.gov.kz/en/industries/social-statistics/stat-edu-science-inno/",
    "https://stat.gov.kz/en/industries/social-statistics/stat-culture/",
    "https://stat.gov.kz/en/industries/business-statistics/stat-industrial-production/",
    "https://stat.gov.kz/en/industries/business-statistics/stat-forrest-village-hunt-fish/",
    "https://stat.gov.kz/en/industries/business-statistics/stat-transport/",
    "https://stat.gov.kz/en/industries/business-statistics/stat-service/",
    "https://stat.gov.kz/en/industries/business-statistics/stat-energy/",
    "https://stat.gov.kz/en/industries/business-statistics/stat-tourism/",
    "https://stat.gov.kz/en/industries/business-statistics/stat-inno-build/",
    "https://stat.gov.kz/en/industries/business-statistics/stat-invest/",
    "https://stat.gov.kz/en/industries/business-statistics/stat-struct/",
    "https://stat.gov.kz/en/industries/business-statistics/stat-org/",
    "https://stat.gov.kz/en/industries/business-statistics/stat-it/",
    "https://stat.gov.kz/en/industries/labor-and-income/stat-empt-unempl/",
    "https://stat.gov.kz/en/industries/labor-and-income/stat-wags/",
    "https://stat.gov.kz/en/industries/labor-and-income/stat-life/",
    "https://stat.gov.kz/en/industries/environment/stat-eco/",
]


print(len(links))
